export const CATEGORIES_EXPENSE = [
  { id: "food", name: "Продукти", icon: "🍕", color: "#C84C5A" },
  { id: "restaurants", name: "Кафе та ресторани", icon: "🍽️", color: "#B45309" },
  { id: "transport", name: "Транспорт", icon: "🚗", color: "#2B6CB0" },
  { id: "taxi", name: "Таксі", icon: "🚕", color: "#CA8A04" },
  { id: "entertainment", name: "Розваги", icon: "🎬", color: "#A16207" },
  { id: "utilities", name: "Комунальні", icon: "💡", color: "#0F766E" },
  { id: "rent", name: "Оренда житла", icon: "🏠", color: "#7C2D12" },
  { id: "internet", name: "Інтернет і зв'язок", icon: "📶", color: "#2563EB" },
  { id: "health", name: "Здоров'я", icon: "⚕️", color: "#B42318" },
  { id: "pharmacy", name: "Аптека", icon: "💊", color: "#BE123C" },
  { id: "shopping", name: "Покупки", icon: "🛍️", color: "#7C3AED" },
  { id: "clothes", name: "Одяг", icon: "👕", color: "#9333EA" },
  { id: "education", name: "Освіта", icon: "📚", color: "#A61E4D" },
  { id: "subscriptions", name: "Підписки", icon: "📱", color: "#4F46E5" },
  { id: "travel", name: "Подорожі", icon: "✈️", color: "#0284C7" },
  { id: "gifts", name: "Подарунки", icon: "🎁", color: "#DB2777" },
  { id: "sport", name: "Спорт", icon: "🏋️", color: "#16A34A" },
  { id: "beauty", name: "Краса", icon: "✨", color: "#C026D3" },
  { id: "repairs", name: "Ремонт", icon: "🔧", color: "#64748B" },
  { id: "insurance", name: "Страхування", icon: "🛡️", color: "#0E7490" },
  { id: "taxes", name: "Податки", icon: "🧾", color: "#334155" },
  { id: "other", name: "Інше", icon: "📌", color: "#475467" },
];

export const CATEGORIES_INCOME = [
  { id: "salary", name: "Зарплата", icon: "💰", color: "#15803D" },
  { id: "freelance", name: "Фріланс", icon: "💻", color: "#0F766E" },
  { id: "bonus", name: "Премія", icon: "🎁", color: "#0369A1" },
  { id: "side-job", name: "Підробіток", icon: "🧰", color: "#047857" },
  { id: "investments", name: "Інвестиції", icon: "📈", color: "#166534" },
  { id: "interest", name: "Відсотки", icon: "🏦", color: "#0E7490" },
  { id: "cashback", name: "Кешбек", icon: "💳", color: "#2563EB" },
  { id: "sales", name: "Продажі", icon: "🛒", color: "#7C2D12" },
  { id: "rental-income", name: "Оренда", icon: "🏘️", color: "#4D7C0F" },
  { id: "gift-income", name: "Подарунки", icon: "🎀", color: "#BE185D" },
  { id: "other-income", name: "Інше", icon: "📈", color: "#1D4ED8" },
];

export const MD3 = {
  primary: "#6750A4",
  onPrimary: "#FFFFFF",
  primaryContainer: "#EADDFF",
  onPrimaryContainer: "#21005D",
  secondaryContainer: "#E8DEF8",
  error: "#B3261E",
  background: "#FFFBFE",
  surface: "#FFFBFE",
  onSurface: "#1C1B1F",
  onSurfaceVariant: "#49454F",
  surfaceVariant: "#E7E0EC",
  surfaceContainer: "#F3EDF7",
  surfaceContainerHigh: "#ECE6F0",
  outlineVariant: "#CAC4D0",
  shadow: "#000000",
  success: "#146C2E",
  successContainer: "#C4EED0",
  errorContainer: "#F9DEDC",
  warning: "#B26A00",
};

export const COLORS = {
  primary: MD3.primary,
  onPrimary: MD3.onPrimary,
  secondary: MD3.success,
  secondaryContainer: MD3.secondaryContainer,
  danger: MD3.error,
  warning: MD3.warning,
  light: MD3.surfaceContainer,
  dark: MD3.onSurface,
  shadow: MD3.shadow,
  text: MD3.onSurface,
  textMuted: MD3.onSurfaceVariant,
  border: MD3.outlineVariant,
  background: MD3.background,
  surface: MD3.surface,
  surfaceVariant: MD3.surfaceVariant,
  surfaceContainer: MD3.surfaceContainer,
  surfaceContainerHigh: MD3.surfaceContainerHigh,
  primaryContainer: MD3.primaryContainer,
  onPrimaryContainer: MD3.onPrimaryContainer,
  successContainer: MD3.successContainer,
  errorContainer: MD3.errorContainer,
};

export const MONTH_NAMES = [
  "Січень",
  "Лютий",
  "Березень",
  "Квітень",
  "Травень",
  "Червень",
  "Липень",
  "Серпень",
  "Вересень",
  "Жовтень",
  "Листопад",
  "Грудень",
];
